### ISSUE TITLE
Crash when running on PDF file

### ISSUE THREAD

**Issue by AndrewHartAR** [prine/ROThumbnailGenerator#3]
I got a crash on this line:
`let thm:UIImage = UIGraphicsGetImageFromCurrentImageContext();`

In the console, all I got was:
`failed to find PDF header:`%PDF' not found.`

**Comment by prine** [comment]
Thanks for reporting. Will look into it as soon as possible!

Somehow this looks familiar to me. There was an Apple bug in iOS 8 which logged the same error.. I will do some researches. Do you also get this error when you run the Example code in the project (ViewController class)? Because the example is running fine with pdfs on my machine.

**Comment by AndrewHartAR** [comment]
Actually - my mistake. I was running it on image data by accident.
